Fix for error message "(...)/.gem/credentials has file permissions of 0644 but 0600 is required."
The change was suggested at https://rubygems.org/profile/edit

The complete error message:

$ gem push (gem)
ERROR:  Your gem push credentials file located at:

	(...)/.gem/credentials

has file permissions of 0644 but 0600 is required.

You should reset your credentials at:

	https://rubygems.org/profile/edit

if you believe they were disclosed to a third party.